Document: ltp
Title: Debian ltp Manual
Author: <insert document author here>
Abstract: This manual describes what ltp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ltp/ltp.sgml.gz

Format: postscript
Files: /usr/share/doc/ltp/ltp.ps.gz

Format: text
Files: /usr/share/doc/ltp/ltp.text.gz

Format: HTML
Index: /usr/share/doc/ltp/html/index.html
Files: /usr/share/doc/ltp/html/*.html
